# Generated by Django 4.2.29 on 2026-03-07 16:50

from django.db import migrations, models
import django_extensions.db.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titel')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='inhoud')),
                ('published', models.BooleanField(default=False, verbose_name='gepubliceerd')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': "Pagina's",
            },
        ),
    ]
