# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-23 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordering', '0082_orderround_transport_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start', models.TimeField(help_text='When this shift starts')),
                ('end', models.TimeField(help_text='When this shifts ends')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('members', models.ManyToManyField(related_name='distribution_shifts', to=settings.AUTH_USER_MODEL)),
                ('order_round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_shifts', to='ordering.OrderRound')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
            },
        ),
    ]
