# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
    ]
