# Generated by Django 3.2.17 on 2023-02-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_auto_20190625_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
