# Generated by Django 3.2.25 on 2025-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0093_alter_orderround_transaction_costs'),
        ('distribution', '0003_alter_shift_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': (['start'],), 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.TimeField(help_text='When this shifts ends (hh:mm)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(help_text='When this shift starts (hh:mm)'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('start', 'end', 'order_round')},
        ),
    ]
