# Generated by Django 3.2.25 on 2025-12-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_auto_20251215_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
    ]
