# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20160315_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='docs/%Y/%m/%d'),
        ),
    ]
