# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-06 19:20
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20181205_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='link',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
