# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-13 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20170502_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='from_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
