# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-15 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailtemplate_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='from_email',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
