# Generated by Django 2.2.28 on 2023-02-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailtemplate_from_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'get_latest_by': 'modified'},
        ),
    ]
