# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_auto_20190415_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='from_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
