# Generated by Django 3.2.17 on 2023-02-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_auto_20230211_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
