# Generated by Django 4.2.29 on 2026-03-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailtemplate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
