# Generated by Django 4.2.29 on 2026-03-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_mailtemplate_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplateTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='templates', to='mailing.mailtemplatetag'),
        ),
    ]
