from django.urls import path, re_path
from .admin_views import (
    OrderAdminMain,
    OrderAdminOrderLists,
    OrderAdminUserOrdersPerProduct,
    OrderAdminUserOrders,
    OrderAdminSupplierOrderCSV,
    OrderAdminUserOrderProductsPerOrderRound,
    OrderAdminCorrection,
    OrderAccounts,
    OrderAdminMassCorrection,
    OrderAdminCorrectionJson,
    UploadProductList,
    CreateDraftProducts,
    CreateRealProducts,
    ProductAdminMain,
    RedirectToMailingView,
    StockAdminView,
    ProductStockApiView,
    ProductApiView,
)

urlpatterns = (
    path("rounds/", OrderAdminMain.as_view(), name="orderadmin_main"),
    path("suppliers/", ProductAdminMain.as_view(), name="productadmin_main"),
    path("stock/", StockAdminView.as_view(), name="stockadmin_main"),
    path("api/productstock/", ProductStockApiView.as_view(), name="ordering.api.productstock"),
    path("api/product/", ProductApiView.as_view(), name="ordering.api.product"),
    path("round/<int:pk>/order_lists/", OrderAdminOrderLists.as_view(), name="orderadmin_orderlists"),
    path(
        "round/<int:pk>/order_lists/<int:supplier_pk>.csv",
        OrderAdminSupplierOrderCSV.as_view(),
        name="orderadmin_supplier_order_csv",
    ),
    path("round/<int:pk>/user_orders/", OrderAdminUserOrders.as_view(), name="orderadmin_userorders"),
    path(
        "round/<int:pk>/product_orders/",
        OrderAdminUserOrderProductsPerOrderRound.as_view(),
        name="orderadmin_orders_per_product",
    ),
    path("round/<int:pk>/correction/json", OrderAdminCorrectionJson.as_view(), name="orderadmin_correction_json"),
    path("round/<int:pk>/correction/mass", OrderAdminMassCorrection.as_view(), name="orderadmin_mass_correction"),
    path("round/<int:pk>/correction/", OrderAdminCorrection.as_view(), name="orderadmin_correction"),
    path("round/<int:pk>/accounts/", OrderAccounts.as_view(), name="orderadmin_accounts"),
    re_path(
        r"^round/(?P<pk>[0-9]+)/mailing/(?P<mailing_type>(round-open))/$",
        RedirectToMailingView.as_view(),
        name="productadmin_mailing",
    ),
    path("product/<int:pk>/", OrderAdminUserOrdersPerProduct.as_view(), name="productorders_admin"),
    path("supplier/<int:supplier>/", CreateDraftProducts.as_view(), name="create_draft_products"),
    path("supplier/<int:supplier>/upload/", UploadProductList.as_view(), name="upload_products"),
    path("supplier/<int:supplier>/finish/", CreateRealProducts.as_view(), name="create_real_products"),
)
