# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-30 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180527_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_drivers_license',
            field=models.BooleanField(default=False),
        ),
    ]
