# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_userprofile_has_drivers_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='share_contact_info',
            field=models.BooleanField(default=False),
        ),
    ]
