# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_userprofile_share_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='vokouser',
            name='activated',
            field=models.DateTimeField(editable=False, help_text='When account was activated', null=True),
        ),
    ]
