# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-07 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('accounts', '0025_vokouser_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_person',
            field=models.OneToOneField(blank=True, help_text='Dit zet je contact gegevens op contact pagina van ledensite.', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Contact persoon voor'),
        ),
    ]
