# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_userprofile_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_person',
            field=models.OneToOneField(blank=True, help_text='Zet contactgegevens op contactpagina van leden site', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Contactpersoon voor'),
        ),
    ]
