# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20190909_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='car_neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='car_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shares_car',
            field=models.BooleanField(default=False, help_text="Dit zet je contactgegevens op transport pagina's van de ledensite", verbose_name='Ik heb een redelijk grote auto die leden kunnen lenen voor transport'),
        ),
    ]
