# Generated by Django 3.2.17 on 2023-03-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20230213_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coordinator_remarks',
            field=models.TextField(blank=True, help_text='Roostervoorkeuren of andere bijzonderheden', max_length=300, null=True, verbose_name='Opmerkingen Coordinator'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='particularities',
            field=models.TextField(blank=True, help_text='Beschikbaarheid of andere bijzonderheden', max_length=300, null=True, verbose_name='Bijzonderheden'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shares_car',
            field=models.BooleanField(help_text="Dit zet je contactgegevens op transport pagina's van de ledensite", verbose_name='Ik heb een redelijk grote auto die leden kunnen lenen voor transport'),
        ),
    ]
