# Generated by Django 3.2.17 on 2023-04-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20230321_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='shares_car',
            field=models.BooleanField(default=False, help_text="Dit zet je contactgegevens op transport pagina's van de ledensite", verbose_name='Ik heb een redelijk grote auto die leden kunnen lenen voor transport'),
        ),
    ]
