# Generated by Django 3.2.25 on 2024-12-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_userprofile_shares_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orderround_mail_optout',
            field=models.BooleanField(default=False, help_text='Je krijgt geen e-mail meer wanneer een bestelronde wordt geopend', verbose_name='Opt-out van bestelronde e-mails'),
        ),
    ]
