# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_ride_order_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='date',
        ),
    ]
