# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0003_remove_ride_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='coordinators',
            field=models.ManyToManyField(related_name='coordinating', to=settings.AUTH_USER_MODEL),
        ),
    ]
