# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-03 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_ride_coordinators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='order_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='ordering.OrderRound'),
        ),
    ]
