# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-22 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20190403_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='coordinators',
        ),
    ]
