# Generated by Django 3.2.17 on 2023-02-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_remove_ride_coordinators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
