# Generated by Django 3.2.20 on 2023-12-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_userprofile_shares_car'),
        ('transport', '0007_auto_20230213_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='codriver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_codriver', to='accounts.readonlyvokouser'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to='accounts.readonlyvokouser'),
        ),
    ]
