# Generated by Django 3.2.25 on 2025-12-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0093_alter_orderround_transaction_costs'),
        ('transport', '0008_auto_20231210_1211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ride',
            unique_together={('order_round', 'route')},
        ),
    ]
