# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0058_auto_20160511_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b'The price the product was sold for', max_digits=6, null=True),
        ),
    ]
