# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 18:23
from __future__ import unicode_literals

from decimal import Decimal, ROUND_UP

from django.db import migrations


# Copied from Product model
def retail_price(order_round, base_price):
    total_percentage = 100 + order_round.markup_percentage
    new_price = (Decimal(base_price) / Decimal('100.0')) * Decimal(total_percentage)
    rounded = new_price.quantize(Decimal('.01'), rounding=ROUND_UP)
    return rounded


def copy_retail_prices(apps, _):
    OrderProduct = apps.get_model("ordering", "OrderProduct")

    for odp in OrderProduct.objects.all():
        retail = retail_price(odp.product.order_round, odp.product.base_price)
        odp.retail_price = retail
        odp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0059_orderproduct_retail_price'),
    ]

    operations = [
        migrations.RunPython(copy_retail_prices)
    ]
