# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0062_auto_20160520_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text=b'The price the product was bought for', max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, help_text=b'The price the product was sold for', max_digits=6),
        ),
    ]
