# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 13:43


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0065_product_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderround',
            name='transaction_costs',
            field=models.DecimalField(decimal_places=2, default=0.21, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='ordering.Product'),
        ),
    ]
