# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-12 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0067_productstock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='type',
            field=models.CharField(choices=[(b'added', b'Added'), (b'lost', b'Lost')], default=(b'added', b'Added'), max_length=5),
        ),
    ]
