# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 13:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0067_productstock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
