# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0068_productstock_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='note',
            new_name='notes',
        ),
    ]
