# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 11:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0069_auto_20161024_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='type',
            field=models.CharField(choices=[(b'added', b'Added'), (b'lost', b'Lost')], db_index=True, default=b'added', max_length=5),
        ),
    ]
