# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0073_auto_20170502_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderround',
            old_name='reminder_hours_before_close',
            new_name='reminder_hours_before_closing',
        ),
    ]
