# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-19 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0074_auto_20170502_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductcorrection',
            name='credit',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='finance.Balance'),
        ),
        migrations.AlterField(
            model_name='orderproductcorrection',
            name='order_product',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='ordering.OrderProduct'),
        ),
        migrations.AlterField(
            model_name='orderproductcorrection',
            name='supplied_percentage',
            field=models.IntegerField(editable=False),
        ),
    ]
