# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0075_auto_20170819_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='supplier',
            name='transport_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
