# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordering', '0076_auto_20190308_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderround',
            name='distribution_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinating_distribution', to=settings.AUTH_USER_MODEL),
        ),
    ]
