# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0078_auto_20190319_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderround',
            name='rides_mails_sent',
            field=models.BooleanField(default=False, editable=False, help_text="Whether we've sent ride info mails"),
        ),
    ]
