# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0080_orderround_rides_mails_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderround',
            name='prepare_ride_mails_sent',
            field=models.BooleanField(default=False, editable=False, help_text="Whether we've sent prepare ride info mails"),
        ),
    ]
