# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-22 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordering', '0081_orderround_prepare_ride_mails_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderround',
            name='transport_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinating_transport_orderrounds', to=settings.AUTH_USER_MODEL),
        ),
    ]
