# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0084_auto_20210818_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderround',
            name='pickup_reminder_sent',
            field=models.BooleanField(default=False, editable=False, help_text="Whether we've sent pickup order reminders to our members"),
        ),
    ]
