# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0085_orderround_pickup_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderround',
            name='reminder_hours_before_pickup',
            field=models.IntegerField(default=4, help_text='Number of hours before collecting time when pickup reminder mail will be sent'),
        ),
    ]
