# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0086_orderround_reminder_hours_before_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderround',
            name='ridecosts_request_mails_sent',
            field=models.BooleanField(default=False, editable=False, help_text="Whether we've sent ridecosts request mails"),
        ),
    ]
