# Generated by Django 2.2.28 on 2022-06-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0087_orderround_ridecosts_request_mails_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderround',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5),
        ),
    ]
