# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0087_orderround_ridecosts_request_mails_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderround',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5),
        ),
    ]
