# Generated by Django 2.2.28 on 2023-02-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0088_auto_20220610_1055'),
        ('ordering', '0088_auto_20230113_1419'),
    ]

    operations = [
    ]
