# Generated by Django 3.2.25 on 2025-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0092_supplier_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderround',
            name='transaction_costs',
            field=models.DecimalField(decimal_places=2, default=0.23, max_digits=5),
        ),
    ]
