# Generated by Django 3.2.17 on 2023-02-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupext',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
