# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_payment_mollie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='qantani_transaction_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='qantani_transaction_id',
            field=models.IntegerField(null=True),
        ),
    ]
