# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 11:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20160617_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.CharField(choices=[(b'CR', b'Credit'), (b'DR', b'Debit')], db_index=True, max_length=2),
        ),
    ]
