# Generated by Django 2.2.28 on 2023-02-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20170502_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'get_latest_by': 'modified'},
        ),
    ]
