---
name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to acceptance'
        required: true
        default: 'main'
        type: string

permissions:
  contents: read

jobs:
  deploy-acceptance:
    name: Deploy to acceptance
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Deploy to acceptance server
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.SSH_KEY }}
          username: voko_acc
          host: leden.vokoutrecht.nl
          script: |
            ~/scripts/deploy.sh ${{ github.event.inputs.branch }}

  deploy-production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'push'
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.SSH_KEY }}
          username: voko
          host: leden.vokoutrecht.nl
          script: |
            ~/scripts/deploy_prod.sh
